export const _keys = {
    UserResponse: () => null,
    LoginResponse: () => null,
    UsersResponse: () => null,

    ItensResponse: () => null,
    ItemResponse: () => null,
    ProjectResponse: () => null,
    RoleRespnse: () => null,
    RolesRespnse: () => null,
    SprintResponse: () => null,
    TeamResponse: () => null,
    Project: () => null,
    Sprint: () => null,
    Role: () => null,
    CommentsResponse: () => null,
    User: () => null,
    authUserResponse: () => null,
    ErrorFieldHandler: () => null,
    TeamsResponse: () => null,
};
